### ISSUE TITLE
ccat won't install due to missing dependency

### ISSUE THREAD

**Issue by remmelt** [jingweno/homebrew-ccat#1]
```
$ brew tap jingweno/ccat
==> Tapping jingweno/ccat
Cloning into '/usr/local/Library/Taps/jingweno/homebrew-ccat'...
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 0), reused 4 (delta 0), pack-reused 0
Unpacking objects: 100% (4/4), done.
Checking connectivity... done.
Tapped 1 formula (26 files, 108K)

$ brew install ccat
==> Installing ccat from jingweno/homebrew-ccat
==> Downloading https://github.com/jingweno/ccat/archive/v0.0.1.tar.gz
######################################################################## 100.0%
==> go build -o ccat
    /usr/local/Cellar/go/1.4.2/libexec/src/github.com/codegangsta/cli (from $GOROOT)
    /Users/remmelt/dev/go/src/github.com/codegangsta/cli (from $GOPATH)
printer.go:7:2: cannot find package "github.com/sourcegraph/syntaxhighlight" in any of:
    /usr/local/Cellar/go/1.4.2/libexec/src/github.com/sourcegraph/syntaxhighlight (from $GOROOT)
    /Users/remmelt/dev/go/src/github.com/sourcegraph/syntaxhighlight (from $GOPATH)

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/jingweno/homebrew-ccat/issues
```

**Comment by andebor** [comment]
I encountered the same issue.

**Comment by remmelt** [comment]
It works after manually installing these dependencies:

```
$ go get github.com/sourcegraph/syntaxhighlight
$ go get github.com/codegangsta/cli

$ brew install ccat
==> Installing ccat from jingweno/homebrew-ccat
==> Downloading https://github.com/jingweno/ccat/archive/v0.0.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/ccat-0.0.1.tar.gz
==> go build -o ccat
🍺  /usr/local/Cellar/ccat/0.0.1: 4 files, 9.0M, built in 2 seconds
```

**Comment by WagnerMatos** [comment]
I've encountered the same issue, tried the solution above and couldn't get it to work.

**Comment by andebor** [comment]
The above mentioned solution worked for me as well. Also had to install hg(mercurial) for the install to complete though. Could you post the error message, @WagnerMatos ?

**Comment by WagnerMatos** [comment]
You're right. Looking at the error I got: `go: missing Mercurial command. See http://golang.org/s/gogetcmd` when tried executing this command: `go get github.com/sourcegraph/syntaxhighlight`

How did you install hg(mercurial)?

**Comment by andebor** [comment]
@WagnerMatos just do 

```
brew install hg
```

**Comment by WagnerMatos** [comment]
@andebor Yeap, these steps worked for me:

`$ brew install hg`
`$ go get github.com/sourcegraph/syntaxhighlight`
`$ go get github.com/codegangsta/cli`
`$ brew install ccat`

Thanks!

**Comment by andebor** [comment]
yeah, it seems like go expects everyone to have mercurial installed. I got it working with the same steps.
Maybe add it as a dependency for the repo?

**Comment by dmitshur** [comment]
Mercurial is needed because at least one of the dependencies uses it. The majority use git however. So you need both for `go get` to be able to fetch everything successfully.

**Comment by owenthereal** [comment]
Sorry for hiccups on the installation. I've made a couple improvements to solve this issue:
- [vendoring dependecies](https://github.com/jingweno/ccat/commit/c230528a85fbf6aadd148f56c71251266b3f8633) so that no `hg` is needed (`git` and `go` are still required)
- introducing a [`build` wrapper script](https://github.com/jingweno/homebrew-ccat/commit/4749f64541d64d003ea549325902250cba4f8eeb) to the main repo so that this formula is more robust

Let me know if you still run into problems :beer:
