### ISSUE TITLE
Issue while installing via brew

### ISSUE THREAD

**Issue by jikkujose** [jingweno/homebrew-ccat#3]
`.gopath/src/github.com/jingweno/ccat/Godeps/_workspace/src/sourcegraph.com/sourcegraph/srclib/store/fs_store.go:680: non-declaration statement outside function body`

**Comment by owenthereal** [comment]
What's your Go version?

```
$ go version
```

You'd need at least 1.4 to compile `ccat`.

**Comment by jikkujose** [comment]
Must be that, this is my version: `go version go1.3.3 darwin/amd64`. But seems thats the highest version available through brew?

**Comment by owenthereal** [comment]
The latest is 1.4.2. Try `brew update && brew upgrade go`

**Comment by jikkujose** [comment]
Yes! My mistake! Its running well now, thanks for the utility, just wish
there was Tomorrow Night theme..

**Comment by owenthereal** [comment]
NP. Customizable theme is in progress: https://github.com/jingweno/ccat#roadmap
